package fast.cloud.nacos.fastcommonnacosgrpcexample.grpc;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcNacosConfig.proto

public final class GrpcNacosProto {
  private GrpcNacosProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(GrpcNacosProto.grpcNacosPort);
    registry.add(GrpcNacosProto.nacosUri);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int GRPC_NACOS_PORT_FIELD_NUMBER = 50001;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      Integer> grpcNacosPort = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Integer.class,
        null);
  public static final int NACOS_URI_FIELD_NUMBER = 50002;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      String> nacosUri = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        String.class,
        null);
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GrpcNacosOptions_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GrpcNacosOptions_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025GrpcNacosConfig.proto\032 google/protobuf" +
      "/descriptor.proto\"3\n\020GrpcNacosOptions:\037\222" +
      "\265\030\025http://127.0.0.1:8848\210\265\030\203\207\003::\n\017grpc_n" +
      "acos_port\022\037.google.protobuf.MessageOptio" +
      "ns\030\321\206\003 \001(\005:4\n\tnacos_uri\022\037.google.protobu" +
      "f.MessageOptions\030\322\206\003 \001(\tB\025B\016GrpcNacosPro" +
      "toP\001\210\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
    internal_static_GrpcNacosOptions_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GrpcNacosOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GrpcNacosOptions_descriptor,
        new String[] { });
    grpcNacosPort.internalInit(descriptor.getExtensions().get(0));
    nacosUri.internalInit(descriptor.getExtensions().get(1));
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(GrpcNacosProto.grpcNacosPort);
    registry.add(GrpcNacosProto.nacosUri);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
