package fast.cloud.nacos.grpc.example.grpc;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcTestService.proto

public interface GrpcTestService_Response_StringOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrpcTestService_Response_String)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   */
  String getResult();
  /**
   * <code>string result = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
