package fast.cloud.nacos.grpc.example.grpc;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcNacosConfig.proto

public interface GrpcNacosOptionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrpcNacosOptions)
    com.google.protobuf.MessageOrBuilder {
}
