package fast.cloud.nacos.grpc.example.grpc;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcTestService.proto

public interface GrpcTestService_Request_StringOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrpcTestService_Request_String)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
